/*
 * GerenciadorDeVendas: PanelPesquisar.java
 * Enconding: UTF-8
 * Data de criação: 18/03/2019 16:33:56
 */
package gerenciadordevendas.telas;

import gerenciadordevendas.tablemodel.TableModelPesquisavel;
import gerenciadordevendas.telas.listener.PesquisarListener;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.util.Optional;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentListener;
import javax.swing.text.AbstractDocument;
import javax.swing.text.Document;

/**
 *
 * @author Ramon Porto
 */
public class PanelPesquisar extends javax.swing.JPanel {

    private TableModelPesquisavel model = null;
    private Window parent;
    private Object objetoSelecionado = null;
    private boolean objetoObtido = false;
    private boolean popupVisible = true;
    private boolean editarBloqueado = false;

    public PanelPesquisar() {
        initComponents();

        selecionarMenu.setVisible(false);
    }

    public final void setModel(TableModelPesquisavel model) {
        this.model = model;
        this.model.setJTable(tabela);
        this.model.atualizaEspacamentoColunas();
        if (this.model.getRowCount() > 0) {
            tabela.setRowSelectionInterval(0, 0);
        }
        removeAllDocumentListeners(campoTextField.getDocument());
        campoTextField.getDocument().addDocumentListener(new PesquisarListener(this.model));
        this.parent = (Window) SwingUtilities.getWindowAncestor(this);
    }

    private void removeAllDocumentListeners(Document doc) {
        if (doc instanceof AbstractDocument) {
            DocumentListener[] listeners = ((AbstractDocument) doc).getDocumentListeners();
            for (DocumentListener listener : listeners) {
                doc.removeDocumentListener(listener);
            }
        }
    }

    public void setSelecionavel(boolean selecionavel) {
        selecionarMenu.setVisible(selecionavel);
    }

    public boolean getSelecionavel() {
        return selecionarMenu.isVisible();
    }

    public Optional getItemSelecionado() {
        setVisible(true);
        if (objetoObtido == false) {
            objetoObtido = true;
        } else {
            return Optional.empty();
        }
        return Optional.ofNullable(objetoSelecionado);
    }

    public PanelPesquisar setPopupVisible(boolean enable) {
        popupVisible = enable;
        return this;
    }

    public void bloquearEditar(boolean b) {
        editarBloqueado = b;
    }

    private void defineObjetoSelecionado() {
        int row = tabela.getSelectedRow();
        if (row > -1) {
            objetoSelecionado = model.getObjetoLinha(row);
            parent.dispose();
        }
    }

    /** This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        selecionarMenu = new javax.swing.JMenuItem();
        editarMenu = new javax.swing.JMenuItem();
        novoMenu = new javax.swing.JMenuItem();
        removerMenu = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        campoTextField = new javax.swing.JTextField();

        selecionarMenu.setText("Selecionar");
        selecionarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarMenuActionPerformed(evt);
            }
        });
        popupMenu.add(selecionarMenu);

        editarMenu.setText("Editar");
        editarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMenuActionPerformed(evt);
            }
        });
        popupMenu.add(editarMenu);

        novoMenu.setText("Novo");
        novoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoMenuActionPerformed(evt);
            }
        });
        popupMenu.add(novoMenu);

        removerMenu.setText("Remover");
        removerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMenuActionPerformed(evt);
            }
        });
        popupMenu.add(removerMenu);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseReleased(evt);
            }
        });

        tabela.setAutoCreateRowSorter(true);
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tabela.setShowHorizontalLines(false);
        tabela.setShowVerticalLines(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        campoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        SwingUtilities.invokeLater(() -> {

            if (SwingUtilities.isRightMouseButton(evt) && popupVisible) {
                int linha = tabela.rowAtPoint(evt.getPoint());
                if (linha >= 0 && linha < tabela.getRowCount()) {
                    tabela.setRowSelectionInterval(linha, linha);
                }

                selecionarMenu.setEnabled(true);
                editarMenu.setEnabled(!editarBloqueado);
                removerMenu.setEnabled(true);
                popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (evt.getClickCount() == 2) {
                if (selecionarMenu.isVisible()) {
                    defineObjetoSelecionado();
                } else {
                    editar();
                }
            }
        });
    }//GEN-LAST:event_tabelaMouseClicked

    private void tabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (selecionarMenu.isVisible()) {
                defineObjetoSelecionado();
            } else {
                editar();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_UP && tabela.getSelectedRow() == 0) {
            campoTextField.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F2 || evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            parent.dispose();
        }
    }//GEN-LAST:event_tabelaKeyPressed

    private void jScrollPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseReleased
        if (SwingUtilities.isRightMouseButton(evt) && popupVisible) {
            selecionarMenu.setEnabled(false);
            editarMenu.setEnabled(false);
            removerMenu.setEnabled(false);
            popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jScrollPane1MouseReleased

    private void campoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (selecionarMenu.isVisible()) {
                defineObjetoSelecionado();
            } else {
                editar();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_F2 || evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            parent.dispose();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            if (model.getRowCount() > 1) {
                tabela.setRowSelectionInterval(1, 1);
            }
            tabela.requestFocus();
        }
    }//GEN-LAST:event_campoTextFieldKeyPressed

    private void selecionarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarMenuActionPerformed
        defineObjetoSelecionado();
    }//GEN-LAST:event_selecionarMenuActionPerformed

    private void editarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMenuActionPerformed
        editar();
    }//GEN-LAST:event_editarMenuActionPerformed

    public void editar() {
        int row = tabela.getSelectedRow();
        if (row > -1) {
            model.editar(parent);
        }
    }

    private void novoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoMenuActionPerformed
        novo();
    }//GEN-LAST:event_novoMenuActionPerformed

    public void novo() {
        model.novo(parent);
    }

    private void removerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMenuActionPerformed
        remover();
    }//GEN-LAST:event_removerMenuActionPerformed

    public void remover() {
        int row = tabela.getSelectedRow();
        if (row > -1) {
            model.remover(parent);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTextField;
    private javax.swing.JMenuItem editarMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem novoMenu;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem removerMenu;
    private javax.swing.JMenuItem selecionarMenu;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
