/*
 * GerenciadorDeVendas: TelaImprimirEtiquetas.java
 * Enconding: UTF-8
 * Data de criação: 15/04/2019 09:02:36
 */
package gerenciadordevendas.telas;

import gerenciadordevendas.controller.EtiquetaJasperReports;
import gerenciadordevendas.model.ItemEstoque;
import java.awt.Dialog;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Ramon Porto
 */
public class TelaImprimirEtiquetas extends javax.swing.JFrame {

    private List<ItemEstoque> itens;
    private EtiquetaJasperReports etiquetaJasperReports = new EtiquetaJasperReports();
    
    public TelaImprimirEtiquetas(List<ItemEstoque> itens) {
//        super(null, Dialog.DEFAULT_MODALITY_TYPE);
        this.itens = itens;
        initComponents();
        Enumeration<AbstractButton> elements = buttonGroup1.getElements();
        int i = 0;
        while (elements.hasMoreElements()) {
            i++;
            AbstractButton next = elements.nextElement();
            next.setName(""+i);
        }
        
    }
    
    public String getSelectedButtonName(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getName();
            }
        }

        return null;
    }

    /** This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jRadioButton46 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton48 = new javax.swing.JRadioButton();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton59 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        jRadioButton61 = new javax.swing.JRadioButton();
        jRadioButton62 = new javax.swing.JRadioButton();
        jRadioButton63 = new javax.swing.JRadioButton();
        jRadioButton64 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        radioVisualizar = new javax.swing.JRadioButton();
        jRadioButton67 = new javax.swing.JRadioButton();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Posição da etiqueta"));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setName("1"); // NOI18N
        jRadioButton1.setPreferredSize(new java.awt.Dimension(21, 21));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton2.setName("2"); // NOI18N

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton3.setName("3"); // NOI18N

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton4.setName("4"); // NOI18N

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton5.setName("5"); // NOI18N

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton6.setName("6"); // NOI18N

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton9.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton10.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton11.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton12.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton13.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton14.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton15.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton16.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton17.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton18.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton19.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton20.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton21.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        jRadioButton22.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton22);
        jRadioButton22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton23.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton23);
        jRadioButton23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        jRadioButton24.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton24);
        jRadioButton24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton25.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton25);
        jRadioButton25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton26.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton26);
        jRadioButton26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton27.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton27);
        jRadioButton27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton28.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton28);
        jRadioButton28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton29.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton29);
        jRadioButton29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton30.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton30);
        jRadioButton30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton31.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton31);
        jRadioButton31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton32.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton32);
        jRadioButton32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton33.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton33);
        jRadioButton33.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton34.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton34);
        jRadioButton34.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton35.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton35);
        jRadioButton35.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton35ActionPerformed(evt);
            }
        });

        jRadioButton36.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton36);
        jRadioButton36.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton37.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton37);
        jRadioButton37.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton38.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton38);
        jRadioButton38.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton38ActionPerformed(evt);
            }
        });

        jRadioButton39.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton39);
        jRadioButton39.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton40.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton40);
        jRadioButton40.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton41.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton41);
        jRadioButton41.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton42.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton42);
        jRadioButton42.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton43.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton43);
        jRadioButton43.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton44.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton44);
        jRadioButton44.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton45.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton45);
        jRadioButton45.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton46.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton46);
        jRadioButton46.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton47.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton47);
        jRadioButton47.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton48.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton48);
        jRadioButton48.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton48.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton49.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton49);
        jRadioButton49.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton50.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton50);
        jRadioButton50.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton51.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton51);
        jRadioButton51.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton52.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton52);
        jRadioButton52.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton53.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton53);
        jRadioButton53.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton54.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton54);
        jRadioButton54.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton55.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton55);
        jRadioButton55.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton56.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton56);
        jRadioButton56.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton57.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton57);
        jRadioButton57.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton57.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton58.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton58);
        jRadioButton58.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton59.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton59);
        jRadioButton59.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton59.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton60.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton60);
        jRadioButton60.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton61.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton61);
        jRadioButton61.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton62.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton62);
        jRadioButton62.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton62.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton63.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton63);
        jRadioButton63.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton63.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButton64.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton64);
        jRadioButton64.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton64.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton64.setName("64"); // NOI18N

        jRadioButton65.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton65);
        jRadioButton65.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton65.setFocusable(false);
        jRadioButton65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton65.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton65.setName("65"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton59, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton59, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRadioButton1.getAccessibleContext().setAccessibleName("1");

        buttonGroup2.add(radioVisualizar);
        radioVisualizar.setSelected(true);
        radioVisualizar.setText("Visualizar impressão");

        buttonGroup2.add(jRadioButton67);
        jRadioButton67.setText("Imprimir");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(radioVisualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton67, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(radioVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton38ActionPerformed

    private void jRadioButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton35ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String posicao = getSelectedButtonName(buttonGroup1);
        
        etiquetaJasperReports.setPosicao(Integer.valueOf(posicao));
        try {
            if (radioVisualizar.isSelected()) {
                etiquetaJasperReports.visualizarEtiquetas(itens);
            } else {
                etiquetaJasperReports.imprimirEtiquetas(itens);
            }
            dispose();
        } catch (JRException ex) {
            Logger.getLogger(TelaImprimirEtiquetas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao gerar a impressão.");
        }
    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton46;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton49;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton61;
    private javax.swing.JRadioButton jRadioButton62;
    private javax.swing.JRadioButton jRadioButton63;
    private javax.swing.JRadioButton jRadioButton64;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton67;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton radioVisualizar;
    // End of variables declaration//GEN-END:variables
}
